'use server';
/**
 * @fileOverview Provides a Genkit flow to find plausible pathology lab information based on a user-provided location.
 * The information is AI-generated for illustrative purposes and should not be considered real-time or factual.
 *
 * - findPathologyLabs - A function that takes a location and returns a list of plausible pathology labs.
 * - FindPathologyLabsInput - The input type for the findPathologyLabs function.
 * - FindPathologyLabsOutput - The return type for the findPathologyLabs function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const FindPathologyLabsInputSchema = z.object({
  location: z.string().describe("The city, zip code, or general area to search for pathology labs."),
});
export type FindPathologyLabsInput = z.infer<typeof FindPathologyLabsInputSchema>;

const PathologyLabSchema = z.object({
  name: z.string().describe("The plausible name of the pathology lab."),
  address: z.string().describe("The plausible full address of the pathology lab."),
  phone: z.string().optional().describe("The plausible phone number of the lab, if available."),
  servicesOffered: z.array(z.string()).optional().describe("A list of plausible common services offered, e.g., 'Blood Tests', 'Urine Analysis', 'Biopsy Processing'."),
  operatingHours: z.string().optional().describe("Plausible operating hours, e.g., 'Mon-Fri 8am-5pm, Sat 8am-12pm'."),
});

const FindPathologyLabsOutputSchema = z.object({
  labs: z
    .array(PathologyLabSchema)
    .describe("A list of plausible pathology labs generated by the AI near the specified location."),
  disclaimer: z
    .string()
    .describe("A disclaimer stating that the information is AI-generated, for illustrative purposes, may not be real or current, and to verify independently."),
  searchedLocation: z.string().describe("The location input provided by the user for the search.")
});
export type FindPathologyLabsOutput = z.infer<typeof FindPathologyLabsOutputSchema>;

export async function findPathologyLabs(input: FindPathologyLabsInput): Promise<FindPathologyLabsOutput> {
  return findPathologyLabsFlow(input);
}

const findPathologyLabsPrompt = ai.definePrompt({
  name: 'findPathologyLabsPrompt',
  input: {schema: FindPathologyLabsInputSchema},
  output: {schema: FindPathologyLabsOutputSchema},
  prompt: `You are an assistant that helps users find pathology labs by generating plausible, illustrative examples.
Based on the provided location: {{{location}}}, generate a list of 2 to 3 plausible pathology lab names, their full addresses, phone numbers (if you can make one up), common services offered (like 'Blood Tests', 'Urine Analysis', 'Biopsy Processing', 'Imaging - X-Ray'), and operating hours.
The generated data should look realistic but is not real.
Ensure the addresses appear reasonable for a general urban or suburban area.

Crucially, you MUST include a 'disclaimer'. The disclaimer should state: "The pathology lab information provided is AI-generated for illustrative purposes only. It may not be real, accurate, or current. Always verify information with official sources and consult with healthcare providers for medical advice."
Also, return the 'searchedLocation' which is the original location input by the user.

Format your response as a JSON object according to the output schema.
  `,
});

const findPathologyLabsFlow = ai.defineFlow(
  {
    name: 'findPathologyLabsFlow',
    inputSchema: FindPathologyLabsInputSchema,
    outputSchema: FindPathologyLabsOutputSchema,
  },
  async (input: FindPathologyLabsInput) => {
    const {output} = await findPathologyLabsPrompt(input);
    return output!;
  }
);
